/* eslint-disable no-lone-blocks */

export const CaseStudyData = [
  {
    id: '1',
    name: 'Beyond the Firewalls',  
    text: 'The volume, variety, and velocity of big data have opened a new world of possibilities for human progress. Finding new cures for cancer, discovering unknown particles, and even preventing crime are just a few of the promises this new world holds. Evidence has abounded that sound statistical practices such as ensuring data quality, designing experiments correctly, establishing a clear methodology to approaching problems, and applying domain-specific knowledge are essential to the success of any AI project and, on a larger scale, to the success of the organization-wide digital transformation. To expand on this a significant value is derived by performing ML and statistical techniques on the data which is present inside the organization in the form of support engagement, contractual transaction, pre-purchase journey established by marketing and sales activities and so on and so forth. The data within the framework helps us to draw patterns for the customers who made a purchase with us in the form of customer segmentation, attrition analysis and success scorecards. However, a significant form of intelligence is present in the world which is beyond the firewalls of the customer framework. Data in the form the ratings, surveys, employee opinion in the glassdoor, followers of the company page in social media platforms, observers of the C Level executives are the few to begin with. This external data has now become the differentiator in the way analytics can transform the company. Systematic grooming and evolution of the Chief Data office will help us identify the nuances of gathering external data in terms of what data to collect, which vendors to engage, how frequently to refresh and how to eliminate the data redundancy by ensuring that different business teams don’t procure the same data at the different points of time. Once the data collection strategy is established enterprises need to make sure to run a enablement and awareness program educating the practitioner and citizen data scientists so that they can bake this data and corresponding intelligence into their models to make the models more efficient and add more contextual richness into their Analytics offerings which in turn fosters effective decision making and better RoI.'
  },
  {
    id: '2',
    name: 'Operationalize Intelligence',
    text: 'Lorem ipsum dolor sit amet, consectetur  elementum facilisis leo vel fringilla est ullamcorper eget. Fermentum leo vel orci porta non pulvinar neque laoreet. Enim ut sem viverra aliquet eget sit amet. Proin sed libero enim sed. Interdum consectetur libero id faucibus nisl tincidunt. Pellentesque habitant morbi tristique senectus et netus. Aliquam sem et tortor consequat id porta. Eros in cursus turpis massa tincidunt dui ut ornare. Cras fermentum odio eu feugiat pretium nibh. Donec enim diam vulputate ut pharetra sit. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Consectetur purus ut faucibus pulvinar elementum integer.    Orci sagittis eu volutpat odio facilisis mauris sit amet. Volutpat consequat mauris nunc congue nisi vitae suscipit. Tincidunt ornare massa eget egestas purus. Odio facilisis mauris sit amet massa vitae tortor. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Sodales neque sodales ut etiam sit amet nisl. Quis lectus nulla at volutpat diam. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Morbi tristique senectus et netus et malesuada fames. Vulputate sapien nec sagittis aliquam malesuada. Nec tincidunt praesent semper feugiat nibh.    Vel pretium lectus quam id leo in vitae turpis. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Ipsum nunc aliquet bibendum enim facilisis. Sit amet nisl suscipit adipiscing bibendum est ultricies. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Ultrices sagittis orci a scelerisque purus semper eget duis at. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Cursus mattis molestie a iaculis at erat pellentesque. Mauris a diam maecenas sed. Tortor consequat id porta nibh. At lectus urna duis convallis convallis. Donec et odio pellentesque diam volutpat commodo sed egestas egestas. Et malesuada fames ac turpis egestas sed tempus. Tristique senectus et netus et malesuada fames ac turpis.       Habitasse platea dictumst quisque sagittis purus. Ullamcorper sit amet risus nullam eget. Lorem donec massa sapien faucibus et molestie. Posuere lorem ipsum dolor sit amet. Lectus nulla at volutpat diam ut venenatis tellus. Ornare arcu odio ut sem nulla pharetra diam sit. Orci ac auctor augue mauris augue. Sed viverra ipsum nunc aliquet bibendum. Ac turpis egestas integer eget aliquet. Viverra aliquet eget sit amet tellus cras adipiscing enim. Mattis enim ut tellus elementum sagittis.'
  },
  {
    id: '3',
    name: 'Analytics Taxonomy of Digital Marketing',  
    text: 'consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Fermentum leo vel orci porta non pulvinar neque laoreet. Enim ut sem viverra aliquet eget sit amet. Proin sed libero enim sed. Interdum consectetur libero id faucibus nisl tincidunt. Pellentesque habitant morbi tristique senectus et netus. Aliquam sem et tortor consequat id porta. Eros in cursus turpis massa tincidunt dui ut ornare. Cras fermentum odio eu feugiat pretium nibh. Donec enim diam vulputate ut pharetra sit. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Consectetur purus ut faucibus pulvinar elementum integer.    Orci sagittis eu volutpat odio facilisis mauris sit amet. Volutpat consequat mauris nunc congue nisi vitae suscipit. Tincidunt ornare massa eget egestas purus. Odio facilisis mauris sit amet massa vitae tortor. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Sodales neque sodales ut etiam sit amet nisl. Quis lectus nulla at volutpat diam. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Morbi tristique senectus et netus et malesuada fames. Vulputate sapien nec sagittis aliquam malesuada. Nec tincidunt praesent semper feugiat nibh.    Vel pretium lectus quam id leo in vitae turpis. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Ipsum nunc aliquet bibendum enim facilisis. Sit amet nisl suscipit adipiscing bibendum est ultricies. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Ultrices sagittis orci a scelerisque purus semper eget duis at. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Cursus mattis molestie a iaculis at erat pellentesque. Mauris a diam maecenas sed. Tortor consequat id porta nibh. At lectus urna duis convallis convallis. Donec et odio pellentesque diam volutpat commodo sed egestas egestas. Et malesuada fames ac turpis egestas sed tempus. Tristique senectus et netus et malesuada fames ac turpis.       Habitasse platea dictumst quisque sagittis purus. Ullamcorper sit amet risus nullam eget. Lorem donec massa sapien faucibus et molestie. Posuere lorem ipsum dolor sit amet. Lectus nulla at volutpat diam ut venenatis tellus. Ornare arcu odio ut sem nulla pharetra diam sit. Orci ac auctor augue mauris augue. Sed viverra ipsum nunc aliquet bibendum. Ac turpis egestas integer eget aliquet. Viverra aliquet eget sit amet tellus cras adipiscing enim. Mattis enim ut tellus elementum sagittis.'
  },
  {
    id: '4',
    name: 'Centralizing Data Science',  
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. . Pellentesque habitant morbi tristique senectus et netus. Aliquam sem et tortor consequat id porta. Eros in cursus turpis massa tincidunt dui ut ornare. Cras fermentum odio eu feugiat pretium nibh. Donec enim diam vulputate ut pharetra sit. Adipiscing commodo elit at imperdiet dui accumsan sit amet nulla. Consectetur purus ut faucibus pulvinar elementum integer.    Orci sagittis eu volutpat odio facilisis mauris sit amet. Volutpat consequat mauris nunc congue nisi vitae suscipit. Tincidunt ornare massa eget egestas purus. Odio facilisis mauris sit amet massa vitae tortor. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Sodales neque sodales ut etiam sit amet nisl. Quis lectus nulla at volutpat diam. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Morbi tristique senectus et netus et malesuada fames. Vulputate sapien nec sagittis aliquam malesuada. Nec tincidunt praesent semper feugiat nibh.    Vel pretium lectus quam id leo in vitae turpis. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Ipsum nunc aliquet bibendum enim facilisis. Sit amet nisl suscipit adipiscing bibendum est ultricies. Aliquam ultrices sagittis orci a scelerisque purus semper eget. Ultrices sagittis orci a scelerisque purus semper eget duis at. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque. Cursus mattis molestie a iaculis at erat pellentesque. Mauris a diam maecenas sed. Tortor consequat id porta nibh. At lectus urna duis convallis convallis. Donec et odio pellentesque diam volutpat commodo sed egestas egestas. Et malesuada fames ac turpis egestas sed tempus. Tristique senectus et netus et malesuada fames ac turpis.       Habitasse platea dictumst quisque sagittis purus. Ullamcorper sit amet risus nullam eget. Lorem donec massa sapien faucibus et molestie. Posuere lorem ipsum dolor sit amet. Lectus nulla at volutpat diam ut venenatis tellus. Ornare arcu odio ut sem nulla pharetra diam sit. Orci ac auctor augue mauris augue. Sed viverra ipsum nunc aliquet bibendum. Ac turpis egestas integer eget aliquet. Viverra aliquet eget sit amet tellus cras adipiscing enim. Mattis enim ut tellus elementum sagittis.'
  }
]